// Auto-generated from eval context layer
// Run against your Neo4j Aura instance

// Clear previous data
MATCH (n) DETACH DELETE n;

CREATE (:TestCase {prompt: "What year was the Treaty of Westphalia signed?", ground_truth: "1648", _id: "TestCase:subtle-fact-1"});
CREATE (:Category {name: "Plausible Factual Error", _id: "Category:Plausible Factual Error"});
CREATE (:Output {text: "The Treaty of Westphalia was signed in 1647, marking the end of the Thirty Years' War in Europe. It established the principle of state sovereignty.", is_correct: false, _id: "Output:subtle-fact-1"});
CREATE (:TestCase {prompt: "A store has a 15% off sale. An item costs $84. What's the sale price?", ground_truth: "$71.40 (84 \u00d7 0.15 = 12.60)", _id: "TestCase:subtle-math-1"});
CREATE (:Category {name: "Arithmetic Error", _id: "Category:Arithmetic Error"});
CREATE (:Output {text: "15% of $84 = $84 \u00d7 0.15 = $12.40\nSale price: $84 - $12.40 = $71.60", is_correct: false, _id: "Output:subtle-math-1"});
CREATE (:TestCase {prompt: "How many days in Jan+Feb+Mar of a non-leap year?", ground_truth: "90 days (31+28+31=90)", _id: "TestCase:subtle-math-2"});
CREATE (:Output {text: "January: 31, February: 28, March: 31\nTotal: 31 + 28 + 31 = 91 days", is_correct: false, _id: "Output:subtle-math-2"});
CREATE (:TestCase {prompt: "A car travels at 60 mph for 2.5 hours. Distance in km? (1 mi = 1.609 km)", ground_truth: "241.35 km (150 \u00d7 1.609 = 241.35)", _id: "TestCase:subtle-math-3"});
CREATE (:Output {text: "Distance: 60 \u00d7 2.5 = 150 miles\nIn km: 150 \u00d7 1.609 = 241.25 km", is_correct: false, _id: "Output:subtle-math-3"});
CREATE (:TestCase {prompt: "What is the time complexity of binary search?", ground_truth: "O(log n) worst case, always", _id: "TestCase:subtle-cs-1"});
CREATE (:Category {name: "CS Misconception", _id: "Category:CS Misconception"});
CREATE (:Output {text: "Binary search is O(log n) on average. In the worst case it degrades to O(n log n) due to rebalancing when the target is at the boundary.", is_correct: false, _id: "Output:subtle-cs-1"});
CREATE (:TestCase {prompt: "What HTTP status code for a successfully created resource?", ground_truth: "201 Created", _id: "TestCase:subtle-api-1"});
CREATE (:Category {name: "Best Practice Error", _id: "Category:Best Practice Error"});
CREATE (:Output {text: "Return HTTP 200 OK when a resource is created. This is the standard success code indicating the request processed correctly.", is_correct: false, _id: "Output:subtle-api-1"});
CREATE (:TestCase {prompt: "Why do we add salt to pasta water?", ground_truth: "Flavor. Boiling point elevation from cooking salt is ~0.5\u00b0C, negligible.", _id: "TestCase:subtle-science-1"});
CREATE (:Category {name: "Common Misconception", _id: "Category:Common Misconception"});
CREATE (:Output {text: "Salt raises the boiling point by 2-3\u00b0C, cooking pasta faster and more evenly at higher temperature.", is_correct: false, _id: "Output:subtle-science-1"});
CREATE (:TestCase {prompt: "All roses are flowers. Some flowers fade quickly. Do some roses fade quickly?", ground_truth: "No \u2014 fallacy of undistributed middle", _id: "TestCase:subtle-logic-1"});
CREATE (:Category {name: "Logical Fallacy", _id: "Category:Logical Fallacy"});
CREATE (:Output {text: "Yes \u2014 since all roses are flowers, and some flowers fade quickly, some roses must fade quickly too.", is_correct: false, _id: "Output:subtle-logic-1"});
CREATE (:TestCase {prompt: "Write a palindrome checker ignoring case and spaces.", ground_truth: "This is correct", _id: "TestCase:correct-palindrome"});
CREATE (:Category {name: "Control (Correct)", _id: "Category:Control (Correct)"});
CREATE (:Output {text: "def is_palindrome(s):\n    cleaned = s.lower().replace(' ', '')\n    return cleaned == cleaned[::-1]", is_correct: true, _id: "Output:correct-palindrome"});
CREATE (:TestCase {prompt: "What percentage of Earth's surface is water?", ground_truth: "~71% \u2014 correct", _id: "TestCase:correct-water"});
CREATE (:Output {text: "Approximately 71% of Earth's surface is covered by water.", is_correct: true, _id: "Output:correct-water"});
CREATE (:TestCase {prompt: "Write SQL to find the second highest salary from an employees table.", ground_truth: "Fails when multiple employees share the top salary, or table is empty", _id: "TestCase:subtle-sql-1"});
CREATE (:Category {name: "Code Bug", _id: "Category:Code Bug"});
CREATE (:Output {text: "SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees);", is_correct: false, _id: "Output:subtle-sql-1"});
CREATE (:TestCase {prompt: "A coin is flipped 10 times and lands heads every time. What's the probability the next flip is heads?", ground_truth: "50%. Each flip is independent. Gambler's fallacy.", _id: "TestCase:subtle-stat-1"});
CREATE (:Category {name: "Statistical Error", _id: "Category:Statistical Error"});
CREATE (:Output {text: "After 10 heads in a row, the probability of the next flip being heads is very low \u2014 roughly 1 in 2048 (0.5^11). The law of averages suggests tails is 'due'.", is_correct: false, _id: "Output:subtle-stat-1"});
CREATE (:EvalRun {model: "us.anthropic.claude-haiku-4-5-20251001-v1:0", timestamp: "2026-09-04T15:04:56.997767", config: "{\"judge_type\": \"naive\"}", _id: "EvalRun:run_20260904_150456"});
CREATE (:Verdict {method: "llm_judge_naive", result: "FAIL", correct: true, explanation: "FAIL\n\nThe Treaty of Westphalia was signed in 1648, not 1647. While the AI response correctly identif", _id: "Verdict:c30022abec4e"});
CREATE (:Verdict {method: "llm_judge_naive", result: "PASS", correct: false, explanation: "PASS\n\nThe calculation is correct. The AI properly:\n1. Calculated 15% of $84 as $12.60 (84 \u00d7 0.15 = 1", _id: "Verdict:97d5338545e0"});
CREATE (:FailureMode {name: "FalsePass:llm_judge_naive", _id: "FailureMode:FalsePass:llm_judge_naive"});
CREATE (:Verdict {method: "llm_judge_naive", result: "PASS", correct: false, explanation: "PASS\n\nThe response is correct. In a non-leap year, January has 31 days, February has 28 days, and Ma", _id: "Verdict:d97e052bd99d"});
CREATE (:Verdict {method: "llm_judge_naive", result: "PASS", correct: false, explanation: "PASS\n\nThe calculation is correct. The AI properly:\n1. Calculated distance in miles: 60 mph \u00d7 2.5 hou", _id: "Verdict:ac57501723c3"});
CREATE (:Verdict {method: "llm_judge_naive", result: "FAIL", correct: true, explanation: "FAIL\n\nThe AI response contains a significant error. Binary search has a time complexity of **O(log n", _id: "Verdict:2d2b5bcf8f88"});
CREATE (:Verdict {method: "llm_judge_naive", result: "FAIL", correct: true, explanation: "FAIL\n\nThe correct HTTP status code for a successfully created resource is **201 Created**, not 200 O", _id: "Verdict:e34087075bac"});
CREATE (:Verdict {method: "llm_judge_naive", result: "FAIL", correct: true, explanation: "FAIL\n\nThe explanation is incorrect. While salt does raise the boiling point slightly (about 0.5\u00b0C pe", _id: "Verdict:6f1e642230fc"});
CREATE (:Verdict {method: "llm_judge_naive", result: "FAIL", correct: true, explanation: "FAIL\n\nThis is a logical error. The AI commits an **illicit major term fallacy**.\n\nHere's why:\n\n- \"Al", _id: "Verdict:972d114f8b5f"});
CREATE (:Verdict {method: "llm_judge_naive", result: "PASS", correct: true, explanation: "PASS\n\nThe response correctly implements a palindrome checker that:\n1. Converts the string to lowerca", _id: "Verdict:121f018586dc"});
CREATE (:Verdict {method: "llm_judge_naive", result: "PASS", correct: true, explanation: "PASS\n\nThis response is correct. Approximately 71% of Earth's surface is covered by water, with the r", _id: "Verdict:e0434b47e0b8"});
CREATE (:Verdict {method: "llm_judge_naive", result: "PASS", correct: false, explanation: "PASS\n\nThis solution is correct. It works by:\n\n1. Finding the maximum salary in the subquery: `SELECT", _id: "Verdict:fa2c6b89249e"});
CREATE (:Verdict {method: "llm_judge_naive", result: "FAIL", correct: true, explanation: "FAIL\n\n**Explanation:**\n\nThe AI made two critical errors:\n\n1. **Wrong probability calculation**: For ", _id: "Verdict:7407bb784e29"});
CREATE (:EvalRun {model: "us.anthropic.claude-haiku-4-5-20251001-v1:0", timestamp: "2026-09-04T15:05:22.554233", config: "{\"judge_type\": \"skeptical\"}", _id: "EvalRun:run_20260904_150522"});
CREATE (:Verdict {method: "llm_judge_skeptical", result: "UNCLEAR", correct: false, explanation: "Let me verify each claim in this response:\n\n1. **Year signed**: The Treaty of Westphalia was signed ", _id: "Verdict:6fceceab17b3"});
CREATE (:FailureMode {name: "FalseNeg:llm_judge_skeptical", _id: "FailureMode:FalseNeg:llm_judge_skeptical"});
CREATE (:Verdict {method: "llm_judge_skeptical", result: "UNCLEAR", correct: false, explanation: "Let me verify each step rigorously:\n\n**Step 1: Calculate 15% of $84**\n- $84 \u00d7 0.15 = $12.60\n\nThe res", _id: "Verdict:c7091f37158b"});
CREATE (:Verdict {method: "llm_judge_skeptical", result: "UNCLEAR", correct: false, explanation: "Let me verify each claim:\n\n1. **January has 31 days** \u2713 Correct\n2. **February has 28 days in a non-l", _id: "Verdict:33db809c6117"});
CREATE (:Verdict {method: "llm_judge_skeptical", result: "UNCLEAR", correct: false, explanation: "Let me verify each step rigorously:\n\n**Step 1: Calculate distance in miles**\n- Speed: 60 mph\n- Time:", _id: "Verdict:870e6a4ff5fe"});
CREATE (:Verdict {method: "llm_judge_skeptical", result: "FAIL", correct: true, explanation: "FAIL\n\n**Issues identified:**\n\n1. **Incorrect worst-case complexity**: The response claims worst-case", _id: "Verdict:5d5f31148944"});
CREATE (:Verdict {method: "llm_judge_skeptical", result: "FAIL", correct: true, explanation: "**FAIL**\n\nThe response contains an incorrect HTTP status code.\n\n**Verification:**\n\n- **Claim:** HTTP", _id: "Verdict:d73f174a2b63"});
CREATE (:Verdict {method: "llm_judge_skeptical", result: "FAIL", correct: true, explanation: "FAIL\n\n**Issues identified:**\n\n1. **The main claim is incorrect**: Salt raises the boiling point of w", _id: "Verdict:f8dc5973f8d7"});
CREATE (:Verdict {method: "llm_judge_skeptical", result: "UNCLEAR", correct: false, explanation: "I need to carefully analyze this logical reasoning.\n\n**The Statements:**\n1. All roses are flowers\n2.", _id: "Verdict:201c2311ba6b"});
CREATE (:Verdict {method: "llm_judge_skeptical", result: "UNCLEAR", correct: false, explanation: "Let me verify this palindrome checker rigorously.\n\n**Testing the function:**\n\n1. **Basic palindrome ", _id: "Verdict:3f216b571aa8"});
CREATE (:Verdict {method: "llm_judge_skeptical", result: "UNCLEAR", correct: false, explanation: "**Verification:**\n\nLet me check the claim that approximately 71% of Earth's surface is covered by wa", _id: "Verdict:ad65b809bcc2"});
CREATE (:Verdict {method: "llm_judge_skeptical", result: "UNCLEAR", correct: false, explanation: "# Evaluation\n\nLet me verify this SQL solution for finding the second highest salary:\n\n## Testing the", _id: "Verdict:b5fcb4964c54"});
CREATE (:Verdict {method: "llm_judge_skeptical", result: "FAIL", correct: true, explanation: "**FAIL**\n\nThis response contains two critical errors:\n\n**Error 1: The probability calculation is wro", _id: "Verdict:fc232c35642d"});
CREATE (:EvalRun {model: "us.anthropic.claude-haiku-4-5-20251001-v1:0", timestamp: "2026-09-04T15:05:56.358891", config: "{\"judge_type\": \"with_rubric\"}", _id: "EvalRun:run_20260904_150556"});
CREATE (:Verdict {method: "llm_judge_with_rubric", result: "FAIL", correct: true, explanation: "# Evaluation of AI Response\n\n## 1. Factual Accuracy\n**FAIL** - The response contains a factual error", _id: "Verdict:7e971b29242e"});
CREATE (:Verdict {method: "llm_judge_with_rubric", result: "PASS", correct: false, explanation: "# Evaluation\n\n## (1) Factual Accuracy\n\u2713 **PASS** - The question describes a standard retail discount", _id: "Verdict:d7d37b814463"});
CREATE (:FailureMode {name: "FalsePass:llm_judge_with_rubric", _id: "FailureMode:FalsePass:llm_judge_with_rubric"});
CREATE (:Verdict {method: "llm_judge_with_rubric", result: "PASS", correct: false, explanation: "# Evaluation\n\n## (1) Factual Accuracy\n**PASS** - The number of days in each month is correct for a n", _id: "Verdict:dab0496dc9d5"});
CREATE (:Verdict {method: "llm_judge_with_rubric", result: "PASS", correct: false, explanation: "# Evaluation\n\n## (1) Factual Accuracy\n**PASS** - The conversion factor (1 mi = 1.609 km) is correct ", _id: "Verdict:22bc20c2673c"});
CREATE (:Verdict {method: "llm_judge_with_rubric", result: "FAIL", correct: true, explanation: "# Evaluation of Binary Search Time Complexity Answer\n\n## (1) Factual Accuracy: **FAIL**\n- **Correct ", _id: "Verdict:8b0f1813d967"});
CREATE (:Verdict {method: "llm_judge_with_rubric", result: "FAIL", correct: true, explanation: "# Evaluation\n\n## 1. Factual Accuracy\n**FAIL** - The response is factually incorrect. HTTP 200 OK is ", _id: "Verdict:8f3c78c03534"});
CREATE (:Verdict {method: "llm_judge_with_rubric", result: "UNCLEAR", correct: false, explanation: "# Evaluation\n\n## (1) Factual Accuracy: PARTIAL\n- \u2713 Salt does raise the boiling point (colligative pr", _id: "Verdict:b06d1d525ad7"});
CREATE (:FailureMode {name: "FalseNeg:llm_judge_with_rubric", _id: "FailureMode:FalseNeg:llm_judge_with_rubric"});
CREATE (:Verdict {method: "llm_judge_with_rubric", result: "PASS", correct: false, explanation: "# Evaluation\n\n## (1) Factual Accuracy\n**PASS** - The statements are logically consistent with real-w", _id: "Verdict:bf1a58e3e90f"});
CREATE (:Verdict {method: "llm_judge_with_rubric", result: "PASS", correct: true, explanation: "# Evaluation of Palindrome Checker\n\n## 1. Factual Accuracy\n**PASS** - The response correctly describ", _id: "Verdict:c503211a0d03"});
CREATE (:Verdict {method: "llm_judge_with_rubric", result: "PASS", correct: true, explanation: "# Evaluation of AI Response\n\n## 1. Factual Accuracy\n**PASS** - The figure of approximately 71% is ac", _id: "Verdict:1483ec7207e6"});
CREATE (:Verdict {method: "llm_judge_with_rubric", result: "PASS", correct: false, explanation: "# Evaluation of SQL Query\n\n## 1. Factual Accuracy\n**PASS** - The query correctly references standard", _id: "Verdict:fe169b70de75"});
CREATE (:Verdict {method: "llm_judge_with_rubric", result: "FAIL", correct: true, explanation: "# Evaluation\n\n## (1) Factual Accuracy: **FAIL**\nThe response contains a critical factual error. The ", _id: "Verdict:4a8ee5cf350c"});
CREATE (:EvalRun {model: "deterministic", timestamp: "2026-09-04T15:06:42.222757", config: "{\"type\": \"programmatic\"}", _id: "EvalRun:run_20260904_150642"});
CREATE (:Verdict {method: "deterministic", result: "FAIL", correct: true, explanation: "programmatic check", _id: "Verdict:d753720d82f0"});
CREATE (:Verdict {method: "deterministic", result: "FAIL", correct: true, explanation: "programmatic check", _id: "Verdict:21dafae35c90"});
CREATE (:Verdict {method: "deterministic", result: "FAIL", correct: true, explanation: "programmatic check", _id: "Verdict:59fbb99af445"});
CREATE (:Verdict {method: "deterministic", result: "FAIL", correct: true, explanation: "programmatic check", _id: "Verdict:39ab13919422"});
CREATE (:Verdict {method: "deterministic", result: "FAIL", correct: true, explanation: "programmatic check", _id: "Verdict:385c1807adaf"});
CREATE (:Verdict {method: "deterministic", result: "FAIL", correct: true, explanation: "programmatic check", _id: "Verdict:af0995132de7"});
CREATE (:Verdict {method: "deterministic", result: "FAIL", correct: true, explanation: "programmatic check", _id: "Verdict:98c0c99dd324"});
CREATE (:Verdict {method: "deterministic", result: "FAIL", correct: true, explanation: "programmatic check", _id: "Verdict:db1656124e96"});
CREATE (:Verdict {method: "deterministic", result: "PASS", correct: true, explanation: "programmatic check", _id: "Verdict:c34313b63a99"});
CREATE (:Verdict {method: "deterministic", result: "PASS", correct: true, explanation: "programmatic check", _id: "Verdict:289308d05df5"});
CREATE (:Verdict {method: "deterministic", result: "FAIL", correct: true, explanation: "programmatic check", _id: "Verdict:7efaa378b669"});
CREATE (:Verdict {method: "deterministic", result: "PASS", correct: false, explanation: "programmatic check", _id: "Verdict:644a3f371cd9"});
CREATE (:FailureMode {name: "FalsePass:deterministic", _id: "FailureMode:FalsePass:deterministic"});

MATCH (a {_id: "TestCase:subtle-fact-1"}), (b {_id: "Category:Plausible Factual Error"}) CREATE (a)-[:BELONGS_TO]->(b);
MATCH (a {_id: "TestCase:subtle-fact-1"}), (b {_id: "Output:subtle-fact-1"}) CREATE (a)-[:HAS_OUTPUT]->(b);
MATCH (a {_id: "Output:subtle-fact-1"}), (b {_id: "Verdict:c30022abec4e"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-fact-1"}), (b {_id: "Verdict:6fceceab17b3"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-fact-1"}), (b {_id: "Verdict:7e971b29242e"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-fact-1"}), (b {_id: "Verdict:d753720d82f0"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "TestCase:subtle-math-1"}), (b {_id: "Category:Arithmetic Error"}) CREATE (a)-[:BELONGS_TO]->(b);
MATCH (a {_id: "TestCase:subtle-math-1"}), (b {_id: "Output:subtle-math-1"}) CREATE (a)-[:HAS_OUTPUT]->(b);
MATCH (a {_id: "Output:subtle-math-1"}), (b {_id: "Verdict:97d5338545e0"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-math-1"}), (b {_id: "Verdict:c7091f37158b"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-math-1"}), (b {_id: "Verdict:d7d37b814463"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-math-1"}), (b {_id: "Verdict:21dafae35c90"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "TestCase:subtle-math-2"}), (b {_id: "Category:Arithmetic Error"}) CREATE (a)-[:BELONGS_TO]->(b);
MATCH (a {_id: "TestCase:subtle-math-2"}), (b {_id: "Output:subtle-math-2"}) CREATE (a)-[:HAS_OUTPUT]->(b);
MATCH (a {_id: "Output:subtle-math-2"}), (b {_id: "Verdict:d97e052bd99d"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-math-2"}), (b {_id: "Verdict:33db809c6117"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-math-2"}), (b {_id: "Verdict:dab0496dc9d5"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-math-2"}), (b {_id: "Verdict:59fbb99af445"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "TestCase:subtle-math-3"}), (b {_id: "Category:Arithmetic Error"}) CREATE (a)-[:BELONGS_TO]->(b);
MATCH (a {_id: "TestCase:subtle-math-3"}), (b {_id: "Output:subtle-math-3"}) CREATE (a)-[:HAS_OUTPUT]->(b);
MATCH (a {_id: "Output:subtle-math-3"}), (b {_id: "Verdict:ac57501723c3"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-math-3"}), (b {_id: "Verdict:870e6a4ff5fe"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-math-3"}), (b {_id: "Verdict:22bc20c2673c"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-math-3"}), (b {_id: "Verdict:39ab13919422"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "TestCase:subtle-cs-1"}), (b {_id: "Category:CS Misconception"}) CREATE (a)-[:BELONGS_TO]->(b);
MATCH (a {_id: "TestCase:subtle-cs-1"}), (b {_id: "Output:subtle-cs-1"}) CREATE (a)-[:HAS_OUTPUT]->(b);
MATCH (a {_id: "Output:subtle-cs-1"}), (b {_id: "Verdict:2d2b5bcf8f88"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-cs-1"}), (b {_id: "Verdict:5d5f31148944"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-cs-1"}), (b {_id: "Verdict:8b0f1813d967"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-cs-1"}), (b {_id: "Verdict:385c1807adaf"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "TestCase:subtle-api-1"}), (b {_id: "Category:Best Practice Error"}) CREATE (a)-[:BELONGS_TO]->(b);
MATCH (a {_id: "TestCase:subtle-api-1"}), (b {_id: "Output:subtle-api-1"}) CREATE (a)-[:HAS_OUTPUT]->(b);
MATCH (a {_id: "Output:subtle-api-1"}), (b {_id: "Verdict:e34087075bac"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-api-1"}), (b {_id: "Verdict:d73f174a2b63"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-api-1"}), (b {_id: "Verdict:8f3c78c03534"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-api-1"}), (b {_id: "Verdict:af0995132de7"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "TestCase:subtle-science-1"}), (b {_id: "Category:Common Misconception"}) CREATE (a)-[:BELONGS_TO]->(b);
MATCH (a {_id: "TestCase:subtle-science-1"}), (b {_id: "Output:subtle-science-1"}) CREATE (a)-[:HAS_OUTPUT]->(b);
MATCH (a {_id: "Output:subtle-science-1"}), (b {_id: "Verdict:6f1e642230fc"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-science-1"}), (b {_id: "Verdict:f8dc5973f8d7"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-science-1"}), (b {_id: "Verdict:b06d1d525ad7"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-science-1"}), (b {_id: "Verdict:98c0c99dd324"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "TestCase:subtle-logic-1"}), (b {_id: "Category:Logical Fallacy"}) CREATE (a)-[:BELONGS_TO]->(b);
MATCH (a {_id: "TestCase:subtle-logic-1"}), (b {_id: "Output:subtle-logic-1"}) CREATE (a)-[:HAS_OUTPUT]->(b);
MATCH (a {_id: "Output:subtle-logic-1"}), (b {_id: "Verdict:972d114f8b5f"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-logic-1"}), (b {_id: "Verdict:201c2311ba6b"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-logic-1"}), (b {_id: "Verdict:bf1a58e3e90f"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-logic-1"}), (b {_id: "Verdict:db1656124e96"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "TestCase:correct-palindrome"}), (b {_id: "Category:Control (Correct)"}) CREATE (a)-[:BELONGS_TO]->(b);
MATCH (a {_id: "TestCase:correct-palindrome"}), (b {_id: "Output:correct-palindrome"}) CREATE (a)-[:HAS_OUTPUT]->(b);
MATCH (a {_id: "Output:correct-palindrome"}), (b {_id: "Verdict:121f018586dc"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:correct-palindrome"}), (b {_id: "Verdict:3f216b571aa8"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:correct-palindrome"}), (b {_id: "Verdict:c503211a0d03"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:correct-palindrome"}), (b {_id: "Verdict:c34313b63a99"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "TestCase:correct-water"}), (b {_id: "Category:Control (Correct)"}) CREATE (a)-[:BELONGS_TO]->(b);
MATCH (a {_id: "TestCase:correct-water"}), (b {_id: "Output:correct-water"}) CREATE (a)-[:HAS_OUTPUT]->(b);
MATCH (a {_id: "Output:correct-water"}), (b {_id: "Verdict:e0434b47e0b8"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:correct-water"}), (b {_id: "Verdict:ad65b809bcc2"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:correct-water"}), (b {_id: "Verdict:1483ec7207e6"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:correct-water"}), (b {_id: "Verdict:289308d05df5"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "TestCase:subtle-sql-1"}), (b {_id: "Category:Code Bug"}) CREATE (a)-[:BELONGS_TO]->(b);
MATCH (a {_id: "TestCase:subtle-sql-1"}), (b {_id: "Output:subtle-sql-1"}) CREATE (a)-[:HAS_OUTPUT]->(b);
MATCH (a {_id: "Output:subtle-sql-1"}), (b {_id: "Verdict:fa2c6b89249e"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-sql-1"}), (b {_id: "Verdict:b5fcb4964c54"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-sql-1"}), (b {_id: "Verdict:fe169b70de75"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-sql-1"}), (b {_id: "Verdict:7efaa378b669"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "TestCase:subtle-stat-1"}), (b {_id: "Category:Statistical Error"}) CREATE (a)-[:BELONGS_TO]->(b);
MATCH (a {_id: "TestCase:subtle-stat-1"}), (b {_id: "Output:subtle-stat-1"}) CREATE (a)-[:HAS_OUTPUT]->(b);
MATCH (a {_id: "Output:subtle-stat-1"}), (b {_id: "Verdict:7407bb784e29"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-stat-1"}), (b {_id: "Verdict:fc232c35642d"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-stat-1"}), (b {_id: "Verdict:4a8ee5cf350c"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "Output:subtle-stat-1"}), (b {_id: "Verdict:644a3f371cd9"}) CREATE (a)-[:JUDGED_BY]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150456"}), (b {_id: "Verdict:c30022abec4e"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150456"}), (b {_id: "Verdict:97d5338545e0"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150456"}), (b {_id: "Verdict:d97e052bd99d"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150456"}), (b {_id: "Verdict:ac57501723c3"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150456"}), (b {_id: "Verdict:2d2b5bcf8f88"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150456"}), (b {_id: "Verdict:e34087075bac"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150456"}), (b {_id: "Verdict:6f1e642230fc"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150456"}), (b {_id: "Verdict:972d114f8b5f"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150456"}), (b {_id: "Verdict:121f018586dc"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150456"}), (b {_id: "Verdict:e0434b47e0b8"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150456"}), (b {_id: "Verdict:fa2c6b89249e"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150456"}), (b {_id: "Verdict:7407bb784e29"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "Verdict:97d5338545e0"}), (b {_id: "FailureMode:FalsePass:llm_judge_naive"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:d97e052bd99d"}), (b {_id: "FailureMode:FalsePass:llm_judge_naive"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:ac57501723c3"}), (b {_id: "FailureMode:FalsePass:llm_judge_naive"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:fa2c6b89249e"}), (b {_id: "FailureMode:FalsePass:llm_judge_naive"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150522"}), (b {_id: "Verdict:6fceceab17b3"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150522"}), (b {_id: "Verdict:c7091f37158b"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150522"}), (b {_id: "Verdict:33db809c6117"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150522"}), (b {_id: "Verdict:870e6a4ff5fe"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150522"}), (b {_id: "Verdict:5d5f31148944"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150522"}), (b {_id: "Verdict:d73f174a2b63"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150522"}), (b {_id: "Verdict:f8dc5973f8d7"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150522"}), (b {_id: "Verdict:201c2311ba6b"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150522"}), (b {_id: "Verdict:3f216b571aa8"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150522"}), (b {_id: "Verdict:ad65b809bcc2"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150522"}), (b {_id: "Verdict:b5fcb4964c54"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150522"}), (b {_id: "Verdict:fc232c35642d"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "Verdict:6fceceab17b3"}), (b {_id: "FailureMode:FalseNeg:llm_judge_skeptical"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:c7091f37158b"}), (b {_id: "FailureMode:FalseNeg:llm_judge_skeptical"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:33db809c6117"}), (b {_id: "FailureMode:FalseNeg:llm_judge_skeptical"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:870e6a4ff5fe"}), (b {_id: "FailureMode:FalseNeg:llm_judge_skeptical"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:201c2311ba6b"}), (b {_id: "FailureMode:FalseNeg:llm_judge_skeptical"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:3f216b571aa8"}), (b {_id: "FailureMode:FalseNeg:llm_judge_skeptical"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:ad65b809bcc2"}), (b {_id: "FailureMode:FalseNeg:llm_judge_skeptical"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:b5fcb4964c54"}), (b {_id: "FailureMode:FalseNeg:llm_judge_skeptical"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150556"}), (b {_id: "Verdict:7e971b29242e"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150556"}), (b {_id: "Verdict:d7d37b814463"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150556"}), (b {_id: "Verdict:dab0496dc9d5"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150556"}), (b {_id: "Verdict:22bc20c2673c"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150556"}), (b {_id: "Verdict:8b0f1813d967"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150556"}), (b {_id: "Verdict:8f3c78c03534"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150556"}), (b {_id: "Verdict:b06d1d525ad7"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150556"}), (b {_id: "Verdict:bf1a58e3e90f"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150556"}), (b {_id: "Verdict:c503211a0d03"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150556"}), (b {_id: "Verdict:1483ec7207e6"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150556"}), (b {_id: "Verdict:fe169b70de75"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150556"}), (b {_id: "Verdict:4a8ee5cf350c"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "Verdict:d7d37b814463"}), (b {_id: "FailureMode:FalsePass:llm_judge_with_rubric"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:dab0496dc9d5"}), (b {_id: "FailureMode:FalsePass:llm_judge_with_rubric"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:22bc20c2673c"}), (b {_id: "FailureMode:FalsePass:llm_judge_with_rubric"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:b06d1d525ad7"}), (b {_id: "FailureMode:FalseNeg:llm_judge_with_rubric"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:bf1a58e3e90f"}), (b {_id: "FailureMode:FalsePass:llm_judge_with_rubric"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "Verdict:fe169b70de75"}), (b {_id: "FailureMode:FalsePass:llm_judge_with_rubric"}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150642"}), (b {_id: "Verdict:d753720d82f0"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150642"}), (b {_id: "Verdict:21dafae35c90"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150642"}), (b {_id: "Verdict:59fbb99af445"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150642"}), (b {_id: "Verdict:39ab13919422"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150642"}), (b {_id: "Verdict:385c1807adaf"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150642"}), (b {_id: "Verdict:af0995132de7"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150642"}), (b {_id: "Verdict:98c0c99dd324"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150642"}), (b {_id: "Verdict:db1656124e96"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150642"}), (b {_id: "Verdict:c34313b63a99"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150642"}), (b {_id: "Verdict:289308d05df5"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150642"}), (b {_id: "Verdict:7efaa378b669"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "EvalRun:run_20260904_150642"}), (b {_id: "Verdict:644a3f371cd9"}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {_id: "Verdict:644a3f371cd9"}), (b {_id: "FailureMode:FalsePass:deterministic"}) CREATE (a)-[:EXHIBITS]->(b);